name: CI devops 2025

on:
  push:
    branches: 
      - main
      - master
  pull_request:

jobs:
  # Job 1 : tester le backend
  test-backend: 
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

       #SonarCloud analysis
      - name: Build, test and analyze with SonarCloud
        run: |
          mvn -B verify sonar:sonar \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.organization=${{ secrets.SONAR_ORG_KEY }} \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            --file ./Java/simpleapi/pom.xml
          
      - name: Build and test with Maven
        run: mvn -f Java/simpleapi/pom.xml clean verify

  # Job 2 : construire et publier l'image Docker
  build-and-push-docker-image:
    needs: test-backend   # s'exécute seulement si le job précédent réussit
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.NAME_DOCKER }}
          password: ${{ secrets.TPDOCKER }}

      - name: Build and push spring-boot Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./Java/simpleapi   # chemin vers le Dockerfile
          push: true
          tags: ${{ secrets.NAME_DOCKER }}/tp-devopssimpleapi:latest
         

      - name: Build database Docker image
        uses: docker/build-push-action@v6
        with:
          context: .  # chemin vers le Dockerfile il est à la racine
          push: true

          tags: ${{ secrets.NAME_DOCKER }}/tp-devopsdatabase:latest

      - name: Build httpd Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./HttpServer 
          push: true
          tags: ${{ secrets.NAME_DOCKER }}/tp-devopshttpd:latest

  deploy-to-server:
    needs: build-and-push-docker-image
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python & Ansible
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip install ansible

      - name: Add SSH private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Run Ansible playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          ansible-playbook -i ansible-tp/inventories/setup.yml ansible-tp/playbook.yml \
            --private-key ~/.ssh/id_rsa \
            -u admin